SPEC_FOLDER=$(ROOT_FOLDER)/Algorithm2

agreement:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Agreement

collision:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Collision

integrity:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Integrity

match-proposal:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) MatchProposal

partial-order:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) PartialOrder

validity:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Validity
