SPEC_FOLDER=$(ROOT_FOLDER)/GenericMulticast1

agreement:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Agreement

collision:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Collision

integrity:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Integrity

partial-order:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) PartialOrder

validity:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Validity
