SPEC_FOLDER=$(ROOT_FOLDER)/GenericMulticast0

agreement:
	sh $(ROOT_FOLDER)/tlc.sh $(SPEC_FOLDER) Agreement

collision:
	sh $(ROOT_FOLDER)/tlc.sh $(SPEC_FOLDER) Collision

integrity:
	sh $(ROOT_FOLDER)/tlc.sh $(SPEC_FOLDER) Integrity

partial-order:
	sh $(ROOT_FOLDER)/tlc.sh $(SPEC_FOLDER) PartialOrder

validity:
	sh $(ROOT_FOLDER)/tlc.sh $(SPEC_FOLDER) Validity

