SPEC_FOLDER=$(ROOT_FOLDER)/GenericMulticast0

agreement:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Agreement

collision:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Collision

integrity:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Integrity

partial-order:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) PartialOrder

strictness:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Strictness

strictness:
	sh $(ROOT_FOLDER)/tlc.sh $(SPEC_FOLDER) Strictness

validity:
	$$0 $(ROOT_FOLDER)/bin/tlc.sh $(SPEC_FOLDER) Validity

